### ISSUE TITLE
new edition hapi 17.2.3 error

### ISSUE THREAD

**Issue by honggang007** [gabaroar/hapi-cors#4]
[1] "name" is required
    at Object.exports.apply (E:\node\yjkzb\manage-api\node_modules\hapi\lib\config.js:22:10)
    at internals.Server.register (E:\node\yjkzb\manage-api\node_modules\hapi\lib\server.js:384:31)
    at init (E:\node\yjkzb\manage-api\server.js:32:18)
    at Object.<anonymous> (E:\node\yjkzb\manage-api\server.js:90:1)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
Hope to update as soon as possible

**Comment by honggang007** [comment]
Have a friend who knows how to solve it, please tell me as soon as possible

**Comment by gabaroar** [comment]
I have updated the code to the latest version of Hapi.
